services:
  backend:
    image: test-site-backend
    pull_policy: never
    container_name: test-site-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  frontend:
    image: test-site-frontend
    pull_policy: never
    container_name: test-site-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"